expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: 65.52.150.215.nip.io
    exposer: Ingress
    http: "true"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: viperfoul.azurecr.io
        TILLER_NAMESPACE: kube-system
PipelineSecrets:
  DockerConfig: '{"auths":{"viperfoul.azurecr.io":{"auth":"dmlwZXJmb3VsOjVsODlWT25sYkk0bjFSclNJV3JRK0lNMXgwTUlUWHNt"}}}'
